
set -g prefix  M-d
set -g base-index 1
set -g renumber-windows on
set -g set-clipboard on
set -g status-position top

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

TMUX_PROJ_SELECT_LAUNCH_KEY="M-p"
TMUX_PROJ_SELECT_DIR="~/work"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#latest'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'safv12/tmux-proj-select'

setw -g mode-keys vi

run '~/.tmux/plugins/tpm/tpm'
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
